stages:
  - build
  - tests
  - deploy

image:
  name: python:3.8.10

building:
  stage: build
  script:
    - echo "hello this is building !"

lint:
  stage: tests
  script:
    - python3 -m pip install pylint
    - python3 -m pylint *.py

unittests:
  stage: tests
  script:
    - echo "hello this is unittesting !"

deploying:
  stage: deploy
  script:
    - echo "hello this is deploying !"

